# Base image is in https://registry.hub.docker.com/_/golang/
# Refer to https://blog.golang.org/docker for usage
FROM leicao/beego

# Install beego & bee
# RUN go get github.com/astaxie/beego
# RUN go get github.com/beego/bee

WORKDIR /go/src/duyDemo